version: "3.8"
services:
  redis:
    container_name: redis
    networks:
      - app-network
    image: redis
    ports:
      - "6379:6379"
  node1:
    networks:
      - app-network
    container_name: "node1"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  node2:
    networks:
      - app-network
    container_name: "node2"
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - node1
      - node2

networks:
  app-network:
    driver: bridge
