version: "3.8"

services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /:/host:ro
  redis:
    container_name: redis
    image: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  node1:
    container_name: node1
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"

  node2:
    container_name: node2
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - node1
      - node2

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - app-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node1
      - node2

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - app-network
    ports:
      - "4000:3000"
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

