global:
  scrape_interval: 15s # 설정된 간격(15초)마다 스크랩

scrape_configs:
  - job_name: 'node1'
    static_configs:
      - targets: ['node1:8000']  # node1 서비스의 주소와 포트
  - job_name: 'node2'
    static_configs:
      - targets: ['node2:3000']  # node2 서비스의 주소와 포트

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Node Exporter의 호스트 이름과 포트
